name: yavc
description: Yet Another Version Checker
version: 1.0.1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # network
  http: ^1.0.0
  url_launcher: ^6.1.11
  lehttp_overrides: ^1.0.2

  # parsing
  html: ^0.15.3

  # persistance
  drift: ^2.8.0
  drift_dev: ^2.8.2
  sqlite3_flutter_libs: ^0.5.15

  # paths
  path: ^1.8.3
  path_provider: ^2.0.15
  file_picker: ^5.3.0

  # animations
  lottie: ^2.3.2

  # additional widgets
  animations: ^2.0.7
  dynamic_height_grid_view: ^0.0.3

  # riverpod
  riverpod: ^2.3.0
  flutter_riverpod: ^2.3.0

  # misc
  intl: ^0.18.1
  window_manager: ^0.3.4
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: "Lato"
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
    - family: "Mono"
      fonts:
        - asset: fonts/ChivoMono-Regular.ttf
        - asset: fonts/ChivoMono-Italic.ttf
          style: italic
        - asset: fonts/ChivoMono-Bold.ttf
          weight: 700
        - asset: fonts/ChivoMono-BoldItalic.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  ios: false
  android: true
  image_path: "assets/icon.png"
  min_sdk_android: 16
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
  web:
    generate: false
