name: "Release"
run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_linux_and_android:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Installing Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: 'Installing Flutter dependencies'
        run: flutter pub get
      - name: 'Installing Linux dependencies'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: 'Linux build'
        run: flutter build linux --release
      - name: 'Android build'
        run: flutter build apk
      - name: 'Removing debug APK and checksums'
        run: |
          rm -rf ./build/app/outputs/flutter-apk/app-debug.apk
          rm -rf ./build/app/outputs/flutter-apk/*.sha1
      - name: 'Signing APK file'
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: ./build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      - name: 'Creating artifacts'
        run: |
          7z a YAVC-Linux.zip ./build/linux/x64/release/bundle/*
          cp ${{steps.sign_app.outputs.signedReleaseFile}} ./YAVC-Android.apk
      - name: 'Generating changelog'
        uses: ardalanamini/auto-changelog@v4
        id: changelog
        with:
          github-token: ${{ github.token }}
          semver: false
          include-compare: false
          mention-authors: false
          mention-new-contributors: false
      - name: 'Uploading release artifacts'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.CUSTOM_GITHUB_TOKEN }}"
        with:
          body: "${{ steps.changelog.outputs.changelog }}"
          files: |
            ./YAVC-Linux.zip
            ./YAVC-Android.apk

  build_windows:
    runs-on: windows-2019
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Installing Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: 'Installing Flutter dependencies'
        run: flutter pub get
      - name: 'Build'
        run: flutter build windows
      - name: 'Create artifact'
        run: 7z a YAVC-Windows.zip ./build/windows/runner/Release/*
      - name: 'Upload release artifacts'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.CUSTOM_GITHUB_TOKEN }}"
        with:
          files: ./YAVC-Windows.zip

  build_macos:
    runs-on: macos-11
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Installing Flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: 'Installing Flutter dependencies'
        run: flutter pub get
      - name: 'Build'
        run: flutter build macos
      - name: 'Create artifact'
        run: 7z a YAVC-MacOS.zip ./build/macos/Build/Products/Release/YAVC.app/
      - name: 'Upload release artifacts'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.CUSTOM_GITHUB_TOKEN }}"
        with:
          files: ./YAVC-MacOS.zip
